Repository router5/router5, pull requests merged in 2018-09, with the labels that each got.

#352 Check if state has meta params before extracting segment params
  packages/router5-transition-path/modules/transitionPath.js
Labels: enhancement

#354 Fix state set in router.replaceHistoryState
  packages/router5/modules/plugins/browser/index.js
Labels: enhancement

#361 Support target="_blank" in BaseLink
  packages/react-router5/modules/BaseLink.js
  packages/react-router5/test/main.js
Labels: enhancement

#365 Add a withRouter component
  packages/react-router5/modules/index.js
  packages/react-router5/modules/withRouter.js
  packages/react-router5/test/main.js
Labels: feature

#364 Don't set state on not mounted component
  packages/react-router5/modules/RouteProvider.js
  packages/react-router5/modules/routeNode.js
  packages/react-router5/modules/withRoute.js
Labels: enhancement, feature
