Repository router5/router5, pull requests merged in 2018-04, with the labels that each got.

#269 Add subscribe function and observable compatibility
  packages/router5/index.d.ts
  packages/router5/modules/core/observable.js
  packages/router5/modules/create-router.js
  packages/router5/package.json
  packages/router5/test/typescript/core/observable.ts
  packages/router5/yarn.lock
Labels: feature

#271 Don't remove trailing slash from pathname when using hash (browser plugin)
  packages/router5/modules/plugins/browser/browser.js
Labels: bug

#272 Smarter route node selector updates
  packages/redux-router5/modules/lib/routeNodeSelector.js
Labels: enhancement

#275 Replace addEventListeners calls with addEventListener
  dist/router5BrowserPlugin.js
  packages/docs/server/public/app.js
  packages/router5/modules/plugins/browser/browser.js
Labels: bug
